language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
    secure: qRGmPNo1DoAl+F2Wbgv1JrS1cBkSNWe8caUv0r1yiHbQtZySsgPo4XQdoQwzzlXPq8fmq+9h5YybDLXuyJccSiIdEFg3EGc9wGexkCSf0HF0FebPEO3An0mrggTXnKMyB/LuMX9gYhNN12iELdPIdacGJSTcpmRtuj9F8gtJgT4Y+Dx85gMFfK0/wJyqm9AN5nUtzz9lqERGEnpOW7qIpvpY0wz4PKp4Kp1hNK43Rv62ltCM+0+pf2NP/BAaYy85T2weo6fl/AIfbUkAM/mqfezziQ0oIi4K57Vhuf9kDviJCSRnb1k7RVclcUA0eDk0WFFWOaZzfIcbPKCkpOEOMjpbOpuUxNdDEV38SyDfpcGs8r8arBJLgFI4bEdH98uupAvfA+1RdIDRF1QAP4+oAF/kXFrDnMZ6i5UmFv1k2cRrJRxky84oOsT/VxpxDedb/+vPlK+Pg7NF0Za00Bs/4mnur+0czYzhev+xLRpastd7F13fr11rTUzUJVSHuHNC/5u9Y9q3JNTCmDEyQw/i7/cnXDGKXLm/dVN5esJQVjoNvRU/l95F2UYSUBqEI33hLxneoz/lz6xIqmuNbvjtB9cQSORSG1BNToyT4lQQcJVudRBoJsQMaUbGGQRTZa9AxmzSFYYctCvNC9iZuQIgC0gFxCHcLxaX61Hb6f9f3Vo=
branches:
  only:
    - source