# Site settings
title: Ordina JWorks Tech Blog
email: info@ordina.be
description: > # this means to ignore newlines until "baseurl:"
  Ordina JWorks Tech blog
metadata:
  keywords: Ordina,ORAJ,JWorks,Blog,Java,Javascript,DevOps
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ordina-jworks.github.io" # the base hostname & protocol for your site
twitter_username: lifeatordinabe
github_username:  ordina-jworks
facebook: lifeatordinabe
gems: [jekyll-paginate, jekyll-feed]
# Build settings
markdown: kramdown

# Pagination
paginate: 10

collections:
    # Needed for our job board
    jobs:
        output: true
        permalink: /jobs/:path/
    