# Site settings
title: Ordina JWorks Tech Blog
email: jworks@ordina.be
description: > # this means to ignore newlines until "baseurl:"
  We build innovative solutions with Java and JavaScript. To support this mission, we have several Competence Centers. From within those Competence Centers, we provide coaching to the employee and expert advice towards our customer. In order to keep in sync with the latest technologies and the latest trends, we frequently visit conferences around the globe.
metadata:
    author: Ordina Belgium
    keywords: Ordina,ORAJ,JWorks,Blog,Java,JavaScript,TypeScript,Angular,DevOps
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ordina-jworks.github.io" # the base hostname & protocol for your site
twitter_username: lifeatordinabe
github_username:  ordina-jworks
facebook: lifeatordinabe
gems: [jekyll-paginate, jekyll-feed]
# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

# Pagination
paginate: 10

collections:
    # Needed for our job board
    jobs:
        output: true
        permalink: /jobs/:path/

defaults:
  - scope:
      path: ""
      type: jobs
    values:
      layout: job